#!/usr/bin/python
"""
    Copyright 2011 Greg L. Turnquist

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

import sys
import os

def java_check(filename):
    file_prefix = filename.split(".class")[0]
    print("Running javap %s" % file_prefix)
    os.system("javap -verbose %s" % file_prefix)
    

if len(sys.argv) > 1:
    for filename in sys.argv[1:]:

        if filename.endswith(".class"):
            java_check(filename)
        else:
            print("We only look at files ending in .class")


else:
    print("No files to process")
